#!/bin/bash

# config
domain=the_subdomain
token=the-api-token
ddns=www.duckdns.org
url="url=https://$ddns/update?domains=$domain&token=$token&ip="

# make call
res=$(echo "$url" | curl -k -K - 2>/dev/null)

# handle res
if [ "$res" != "OK" ]; then
    echo "[$(date)]: Error with duckdns script: $res" >> ~/error.log
fi
