#!/usr/bin/env bash

vhome_dir="$(dirname "$(badrealpath $0 2>/dev/null || echo $0)")"
cd "$vhome_dir" || {
    echo "Failed to cd into vhome dir: $vhome_dir"
    exit 1
}

if [ "$1" != 'force' ]; then
    echo "NOTE: Add 'force' as FIRST argument to actually install"
    dryrun='--dry-run'
else
    shift
fi

echo "*** Installing ***"
echo
rsync -rav $dryrun skel/ ~/
echo

if [ $# = 0 ]; then
    echo "Available workspaces:"
    ls ws
    exit
fi

for ws in "$@"; do
    echo
    echo "*** Applying workspace $ws ***"
    echo
    if [ -d "ws/$ws" ]; then
        mkdir -p "$HOME/.ws/$ws/"
        rsync -rav $dryrun "ws/$ws/" "$HOME/.ws/$ws/"
    else
        echo "Bad workspace: $ws"
    fi
done

