#!/bin/bash

apt-get update
apt-get install -y exfat-fuse exfat-utils

hostname core
echo core > /etc/hostname
sed -i -e 's/raspberrypi/core/g' /etc/hosts

# raspi-config

# Setup crontab as well
*/5 * * * * ~root/duck &>/dev/null
